#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoWeb_Oscar
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BD_PROYECTO_WEB")]
	public partial class BD_ProyectoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertDETALLE_PEDIDOS(DETALLE_PEDIDOS instance);
    partial void UpdateDETALLE_PEDIDOS(DETALLE_PEDIDOS instance);
    partial void DeleteDETALLE_PEDIDOS(DETALLE_PEDIDOS instance);
    partial void InsertPEDIDOS(PEDIDOS instance);
    partial void UpdatePEDIDOS(PEDIDOS instance);
    partial void DeletePEDIDOS(PEDIDOS instance);
    partial void InsertSUPLEMENTOS_CATEGORIAS(SUPLEMENTOS_CATEGORIAS instance);
    partial void UpdateSUPLEMENTOS_CATEGORIAS(SUPLEMENTOS_CATEGORIAS instance);
    partial void DeleteSUPLEMENTOS_CATEGORIAS(SUPLEMENTOS_CATEGORIAS instance);
    partial void InsertUSUARIOS(USUARIOS instance);
    partial void UpdateUSUARIOS(USUARIOS instance);
    partial void DeleteUSUARIOS(USUARIOS instance);
    partial void InsertCATEGORIAS(CATEGORIAS instance);
    partial void UpdateCATEGORIAS(CATEGORIAS instance);
    partial void DeleteCATEGORIAS(CATEGORIAS instance);
    partial void InsertSUPLEMENTOS(SUPLEMENTOS instance);
    partial void UpdateSUPLEMENTOS(SUPLEMENTOS instance);
    partial void DeleteSUPLEMENTOS(SUPLEMENTOS instance);
    #endregion
		
		public BD_ProyectoDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BD_PROYECTO_WEBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BD_ProyectoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BD_ProyectoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BD_ProyectoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BD_ProyectoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DETALLE_PEDIDOS> DETALLE_PEDIDOS
		{
			get
			{
				return this.GetTable<DETALLE_PEDIDOS>();
			}
		}
		
		public System.Data.Linq.Table<PEDIDOS> PEDIDOS
		{
			get
			{
				return this.GetTable<PEDIDOS>();
			}
		}
		
		public System.Data.Linq.Table<SUPLEMENTOS_CATEGORIAS> SUPLEMENTOS_CATEGORIAS
		{
			get
			{
				return this.GetTable<SUPLEMENTOS_CATEGORIAS>();
			}
		}
		
		public System.Data.Linq.Table<USUARIOS> USUARIOS
		{
			get
			{
				return this.GetTable<USUARIOS>();
			}
		}
		
		public System.Data.Linq.Table<CATEGORIAS> CATEGORIAS
		{
			get
			{
				return this.GetTable<CATEGORIAS>();
			}
		}
		
		public System.Data.Linq.Table<SUPLEMENTOS> SUPLEMENTOS
		{
			get
			{
				return this.GetTable<SUPLEMENTOS>();
			}
		}
		
		public System.Data.Linq.Table<VistaSuplementos> VistaSuplementos
		{
			get
			{
				return this.GetTable<VistaSuplementos>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_AGREGAR_PRODUCTO_PEDIDO")]
		public int SP_AGREGAR_PRODUCTO_PEDIDO([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idPedido, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idSuplemento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cantidad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MSJ", DbType="VarChar(50)")] ref string mSJ)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idPedido, idSuplemento, cantidad, mSJ);
			mSJ = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EDITAR_USUARIO")]
		public int SP_EDITAR_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE", DbType="VarChar(50)")] string nOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO", DbType="VarChar(50)")] string cORREO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CLAVE", DbType="VarChar(50)")] string cLAVE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MSJ", DbType="VarChar(50)")] ref string mSJ)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, nOMBRE, cORREO, cLAVE, mSJ);
			mSJ = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_PEDIDO_ENVIADO")]
		public int SP_PEDIDO_ENVIADO([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idPedido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MSJ", DbType="VarChar(50)")] ref string mSJ)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idPedido, mSJ);
			mSJ = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_AGREGAR_CATEGORIA")]
		public int SP_AGREGAR_CATEGORIA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE", DbType="VarChar(50)")] string nOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MSJ", DbType="VarChar(50)")] ref string mSJ)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nOMBRE, mSJ);
			mSJ = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_AGREGAR_USUARIO")]
		public int SP_AGREGAR_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE", DbType="VarChar(50)")] string nOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO", DbType="VarChar(50)")] string cORREO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CLAVE", DbType="VarChar(50)")] string cLAVE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MSJ", DbType="VarChar(50)")] ref string mSJ)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nOMBRE, cORREO, cLAVE, mSJ);
			mSJ = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_AGREGAR_SUPLEMENTO")]
		public int SP_AGREGAR_SUPLEMENTO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CATEGORIA", DbType="Int")] System.Nullable<int> cATEGORIA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE", DbType="VarChar(50)")] string nOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DESCRIPCION", DbType="VarChar(200)")] string dESCRIPCION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRECIO", DbType="Money")] System.Nullable<decimal> pRECIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CANTIDAD", DbType="Int")] System.Nullable<int> cANTIDAD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MSJ", DbType="VarChar(50)")] ref string mSJ, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string rutaImagen)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cATEGORIA, nOMBRE, dESCRIPCION, pRECIO, cANTIDAD, mSJ, rutaImagen);
			mSJ = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EDITAR_SUPLEMENTO")]
		public int SP_EDITAR_SUPLEMENTO([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE", DbType="VarChar(50)")] string nOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DESCRIPCION", DbType="VarChar(200)")] string dESCRIPCION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRECIO", DbType="Money")] System.Nullable<decimal> pRECIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CANTIDAD", DbType="Int")] System.Nullable<int> cANTIDAD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MSJ", DbType="VarChar(50)")] ref string mSJ, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string ruta)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, nOMBRE, dESCRIPCION, pRECIO, cANTIDAD, mSJ, ruta);
			mSJ = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_CREAR_PEDIDO")]
		public int SP_CREAR_PEDIDO([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MSJ", DbType="VarChar(50)")] ref string mSJ)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, mSJ);
			mSJ = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Eliminar_PRODUCTOS_PEDIDO")]
		public int SP_Eliminar_PRODUCTOS_PEDIDO([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idPedido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MSJ", DbType="VarChar(50)")] ref string mSJ)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idPedido, mSJ);
			mSJ = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EDITAR_PEDIDO")]
		public int SP_EDITAR_PEDIDO([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idDetallePedido, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idSuplemento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cantidad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MSJ", DbType="VarChar(50)")] ref string mSJ, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1)")] ref string retorno)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idDetallePedido, idSuplemento, cantidad, mSJ, retorno);
			mSJ = ((string)(result.GetParameterValue(3)));
			retorno = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DETALLE_PEDIDOS")]
	public partial class DETALLE_PEDIDOS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_DETALLE_PEDIDO;
		
		private int _ID_PEDIDO;
		
		private int _ID_SUPLEMENTO;
		
		private int _CANTIDAD_SOLICITADA;
		
		private EntityRef<PEDIDOS> _PEDIDOS;
		
		private EntityRef<SUPLEMENTOS> _SUPLEMENTOS;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_DETALLE_PEDIDOChanging(int value);
    partial void OnID_DETALLE_PEDIDOChanged();
    partial void OnID_PEDIDOChanging(int value);
    partial void OnID_PEDIDOChanged();
    partial void OnID_SUPLEMENTOChanging(int value);
    partial void OnID_SUPLEMENTOChanged();
    partial void OnCANTIDAD_SOLICITADAChanging(int value);
    partial void OnCANTIDAD_SOLICITADAChanged();
    #endregion
		
		public DETALLE_PEDIDOS()
		{
			this._PEDIDOS = default(EntityRef<PEDIDOS>);
			this._SUPLEMENTOS = default(EntityRef<SUPLEMENTOS>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DETALLE_PEDIDO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_DETALLE_PEDIDO
		{
			get
			{
				return this._ID_DETALLE_PEDIDO;
			}
			set
			{
				if ((this._ID_DETALLE_PEDIDO != value))
				{
					this.OnID_DETALLE_PEDIDOChanging(value);
					this.SendPropertyChanging();
					this._ID_DETALLE_PEDIDO = value;
					this.SendPropertyChanged("ID_DETALLE_PEDIDO");
					this.OnID_DETALLE_PEDIDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PEDIDO", DbType="Int NOT NULL")]
		public int ID_PEDIDO
		{
			get
			{
				return this._ID_PEDIDO;
			}
			set
			{
				if ((this._ID_PEDIDO != value))
				{
					if (this._PEDIDOS.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_PEDIDOChanging(value);
					this.SendPropertyChanging();
					this._ID_PEDIDO = value;
					this.SendPropertyChanged("ID_PEDIDO");
					this.OnID_PEDIDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_SUPLEMENTO", DbType="Int NOT NULL")]
		public int ID_SUPLEMENTO
		{
			get
			{
				return this._ID_SUPLEMENTO;
			}
			set
			{
				if ((this._ID_SUPLEMENTO != value))
				{
					if (this._SUPLEMENTOS.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_SUPLEMENTOChanging(value);
					this.SendPropertyChanging();
					this._ID_SUPLEMENTO = value;
					this.SendPropertyChanged("ID_SUPLEMENTO");
					this.OnID_SUPLEMENTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CANTIDAD_SOLICITADA", DbType="Int NOT NULL")]
		public int CANTIDAD_SOLICITADA
		{
			get
			{
				return this._CANTIDAD_SOLICITADA;
			}
			set
			{
				if ((this._CANTIDAD_SOLICITADA != value))
				{
					this.OnCANTIDAD_SOLICITADAChanging(value);
					this.SendPropertyChanging();
					this._CANTIDAD_SOLICITADA = value;
					this.SendPropertyChanged("CANTIDAD_SOLICITADA");
					this.OnCANTIDAD_SOLICITADAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PEDIDOS_DETALLE_PEDIDOS", Storage="_PEDIDOS", ThisKey="ID_PEDIDO", OtherKey="ID_PEDIDO", IsForeignKey=true)]
		public PEDIDOS PEDIDOS
		{
			get
			{
				return this._PEDIDOS.Entity;
			}
			set
			{
				PEDIDOS previousValue = this._PEDIDOS.Entity;
				if (((previousValue != value) 
							|| (this._PEDIDOS.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PEDIDOS.Entity = null;
						previousValue.DETALLE_PEDIDOS.Remove(this);
					}
					this._PEDIDOS.Entity = value;
					if ((value != null))
					{
						value.DETALLE_PEDIDOS.Add(this);
						this._ID_PEDIDO = value.ID_PEDIDO;
					}
					else
					{
						this._ID_PEDIDO = default(int);
					}
					this.SendPropertyChanged("PEDIDOS");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SUPLEMENTOS_DETALLE_PEDIDOS", Storage="_SUPLEMENTOS", ThisKey="ID_SUPLEMENTO", OtherKey="ID_SUPLEMENTO", IsForeignKey=true)]
		public SUPLEMENTOS SUPLEMENTOS
		{
			get
			{
				return this._SUPLEMENTOS.Entity;
			}
			set
			{
				SUPLEMENTOS previousValue = this._SUPLEMENTOS.Entity;
				if (((previousValue != value) 
							|| (this._SUPLEMENTOS.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SUPLEMENTOS.Entity = null;
						previousValue.DETALLE_PEDIDOS.Remove(this);
					}
					this._SUPLEMENTOS.Entity = value;
					if ((value != null))
					{
						value.DETALLE_PEDIDOS.Add(this);
						this._ID_SUPLEMENTO = value.ID_SUPLEMENTO;
					}
					else
					{
						this._ID_SUPLEMENTO = default(int);
					}
					this.SendPropertyChanged("SUPLEMENTOS");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PEDIDOS")]
	public partial class PEDIDOS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_PEDIDO;
		
		private int _ID_USUARIO;
		
		private System.DateTime _FECHA_PEDIDO;
		
		private string _ESTADO;
		
		private EntitySet<DETALLE_PEDIDOS> _DETALLE_PEDIDOS;
		
		private EntityRef<USUARIOS> _USUARIOS;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_PEDIDOChanging(int value);
    partial void OnID_PEDIDOChanged();
    partial void OnID_USUARIOChanging(int value);
    partial void OnID_USUARIOChanged();
    partial void OnFECHA_PEDIDOChanging(System.DateTime value);
    partial void OnFECHA_PEDIDOChanged();
    partial void OnESTADOChanging(string value);
    partial void OnESTADOChanged();
    #endregion
		
		public PEDIDOS()
		{
			this._DETALLE_PEDIDOS = new EntitySet<DETALLE_PEDIDOS>(new Action<DETALLE_PEDIDOS>(this.attach_DETALLE_PEDIDOS), new Action<DETALLE_PEDIDOS>(this.detach_DETALLE_PEDIDOS));
			this._USUARIOS = default(EntityRef<USUARIOS>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PEDIDO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_PEDIDO
		{
			get
			{
				return this._ID_PEDIDO;
			}
			set
			{
				if ((this._ID_PEDIDO != value))
				{
					this.OnID_PEDIDOChanging(value);
					this.SendPropertyChanging();
					this._ID_PEDIDO = value;
					this.SendPropertyChanged("ID_PEDIDO");
					this.OnID_PEDIDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USUARIO", DbType="Int NOT NULL")]
		public int ID_USUARIO
		{
			get
			{
				return this._ID_USUARIO;
			}
			set
			{
				if ((this._ID_USUARIO != value))
				{
					if (this._USUARIOS.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_USUARIOChanging(value);
					this.SendPropertyChanging();
					this._ID_USUARIO = value;
					this.SendPropertyChanged("ID_USUARIO");
					this.OnID_USUARIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_PEDIDO", DbType="Date NOT NULL")]
		public System.DateTime FECHA_PEDIDO
		{
			get
			{
				return this._FECHA_PEDIDO;
			}
			set
			{
				if ((this._FECHA_PEDIDO != value))
				{
					this.OnFECHA_PEDIDOChanging(value);
					this.SendPropertyChanging();
					this._FECHA_PEDIDO = value;
					this.SendPropertyChanged("FECHA_PEDIDO");
					this.OnFECHA_PEDIDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this.OnESTADOChanging(value);
					this.SendPropertyChanging();
					this._ESTADO = value;
					this.SendPropertyChanged("ESTADO");
					this.OnESTADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PEDIDOS_DETALLE_PEDIDOS", Storage="_DETALLE_PEDIDOS", ThisKey="ID_PEDIDO", OtherKey="ID_PEDIDO")]
		public EntitySet<DETALLE_PEDIDOS> DETALLE_PEDIDOS
		{
			get
			{
				return this._DETALLE_PEDIDOS;
			}
			set
			{
				this._DETALLE_PEDIDOS.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="USUARIOS_PEDIDOS", Storage="_USUARIOS", ThisKey="ID_USUARIO", OtherKey="ID_USUARIO", IsForeignKey=true)]
		public USUARIOS USUARIOS
		{
			get
			{
				return this._USUARIOS.Entity;
			}
			set
			{
				USUARIOS previousValue = this._USUARIOS.Entity;
				if (((previousValue != value) 
							|| (this._USUARIOS.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._USUARIOS.Entity = null;
						previousValue.PEDIDOS.Remove(this);
					}
					this._USUARIOS.Entity = value;
					if ((value != null))
					{
						value.PEDIDOS.Add(this);
						this._ID_USUARIO = value.ID_USUARIO;
					}
					else
					{
						this._ID_USUARIO = default(int);
					}
					this.SendPropertyChanged("USUARIOS");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DETALLE_PEDIDOS(DETALLE_PEDIDOS entity)
		{
			this.SendPropertyChanging();
			entity.PEDIDOS = this;
		}
		
		private void detach_DETALLE_PEDIDOS(DETALLE_PEDIDOS entity)
		{
			this.SendPropertyChanging();
			entity.PEDIDOS = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SUPLEMENTOS_CATEGORIAS")]
	public partial class SUPLEMENTOS_CATEGORIAS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_SUPLEMENTO;
		
		private int _ID_CATEGORIA;
		
		private EntityRef<CATEGORIAS> _CATEGORIAS;
		
		private EntityRef<SUPLEMENTOS> _SUPLEMENTOS;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_SUPLEMENTOChanging(int value);
    partial void OnID_SUPLEMENTOChanged();
    partial void OnID_CATEGORIAChanging(int value);
    partial void OnID_CATEGORIAChanged();
    #endregion
		
		public SUPLEMENTOS_CATEGORIAS()
		{
			this._CATEGORIAS = default(EntityRef<CATEGORIAS>);
			this._SUPLEMENTOS = default(EntityRef<SUPLEMENTOS>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_SUPLEMENTO", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_SUPLEMENTO
		{
			get
			{
				return this._ID_SUPLEMENTO;
			}
			set
			{
				if ((this._ID_SUPLEMENTO != value))
				{
					if (this._SUPLEMENTOS.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_SUPLEMENTOChanging(value);
					this.SendPropertyChanging();
					this._ID_SUPLEMENTO = value;
					this.SendPropertyChanged("ID_SUPLEMENTO");
					this.OnID_SUPLEMENTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CATEGORIA", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_CATEGORIA
		{
			get
			{
				return this._ID_CATEGORIA;
			}
			set
			{
				if ((this._ID_CATEGORIA != value))
				{
					if (this._CATEGORIAS.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_CATEGORIAChanging(value);
					this.SendPropertyChanging();
					this._ID_CATEGORIA = value;
					this.SendPropertyChanged("ID_CATEGORIA");
					this.OnID_CATEGORIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CATEGORIAS_SUPLEMENTOS_CATEGORIAS", Storage="_CATEGORIAS", ThisKey="ID_CATEGORIA", OtherKey="ID_CATEGORIA", IsForeignKey=true)]
		public CATEGORIAS CATEGORIAS
		{
			get
			{
				return this._CATEGORIAS.Entity;
			}
			set
			{
				CATEGORIAS previousValue = this._CATEGORIAS.Entity;
				if (((previousValue != value) 
							|| (this._CATEGORIAS.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CATEGORIAS.Entity = null;
						previousValue.SUPLEMENTOS_CATEGORIAS.Remove(this);
					}
					this._CATEGORIAS.Entity = value;
					if ((value != null))
					{
						value.SUPLEMENTOS_CATEGORIAS.Add(this);
						this._ID_CATEGORIA = value.ID_CATEGORIA;
					}
					else
					{
						this._ID_CATEGORIA = default(int);
					}
					this.SendPropertyChanged("CATEGORIAS");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SUPLEMENTOS_SUPLEMENTOS_CATEGORIAS", Storage="_SUPLEMENTOS", ThisKey="ID_SUPLEMENTO", OtherKey="ID_SUPLEMENTO", IsForeignKey=true)]
		public SUPLEMENTOS SUPLEMENTOS
		{
			get
			{
				return this._SUPLEMENTOS.Entity;
			}
			set
			{
				SUPLEMENTOS previousValue = this._SUPLEMENTOS.Entity;
				if (((previousValue != value) 
							|| (this._SUPLEMENTOS.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SUPLEMENTOS.Entity = null;
						previousValue.SUPLEMENTOS_CATEGORIAS.Remove(this);
					}
					this._SUPLEMENTOS.Entity = value;
					if ((value != null))
					{
						value.SUPLEMENTOS_CATEGORIAS.Add(this);
						this._ID_SUPLEMENTO = value.ID_SUPLEMENTO;
					}
					else
					{
						this._ID_SUPLEMENTO = default(int);
					}
					this.SendPropertyChanged("SUPLEMENTOS");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.USUARIOS")]
	public partial class USUARIOS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_USUARIO;
		
		private string _NOMBRE;
		
		private string _CORREO;
		
		private string _CLAVE;
		
		private EntitySet<PEDIDOS> _PEDIDOS;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_USUARIOChanging(int value);
    partial void OnID_USUARIOChanged();
    partial void OnNOMBREChanging(string value);
    partial void OnNOMBREChanged();
    partial void OnCORREOChanging(string value);
    partial void OnCORREOChanged();
    partial void OnCLAVEChanging(string value);
    partial void OnCLAVEChanged();
    #endregion
		
		public USUARIOS()
		{
			this._PEDIDOS = new EntitySet<PEDIDOS>(new Action<PEDIDOS>(this.attach_PEDIDOS), new Action<PEDIDOS>(this.detach_PEDIDOS));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USUARIO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_USUARIO
		{
			get
			{
				return this._ID_USUARIO;
			}
			set
			{
				if ((this._ID_USUARIO != value))
				{
					this.OnID_USUARIOChanging(value);
					this.SendPropertyChanging();
					this._ID_USUARIO = value;
					this.SendPropertyChanged("ID_USUARIO");
					this.OnID_USUARIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this.OnNOMBREChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE = value;
					this.SendPropertyChanged("NOMBRE");
					this.OnNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORREO", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CORREO
		{
			get
			{
				return this._CORREO;
			}
			set
			{
				if ((this._CORREO != value))
				{
					this.OnCORREOChanging(value);
					this.SendPropertyChanging();
					this._CORREO = value;
					this.SendPropertyChanged("CORREO");
					this.OnCORREOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLAVE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CLAVE
		{
			get
			{
				return this._CLAVE;
			}
			set
			{
				if ((this._CLAVE != value))
				{
					this.OnCLAVEChanging(value);
					this.SendPropertyChanging();
					this._CLAVE = value;
					this.SendPropertyChanged("clave");
					this.OnCLAVEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="USUARIOS_PEDIDOS", Storage="_PEDIDOS", ThisKey="ID_USUARIO", OtherKey="ID_USUARIO")]
		public EntitySet<PEDIDOS> PEDIDOS
		{
			get
			{
				return this._PEDIDOS;
			}
			set
			{
				this._PEDIDOS.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PEDIDOS(PEDIDOS entity)
		{
			this.SendPropertyChanging();
			entity.USUARIOS = this;
		}
		
		private void detach_PEDIDOS(PEDIDOS entity)
		{
			this.SendPropertyChanging();
			entity.USUARIOS = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CATEGORIAS")]
	public partial class CATEGORIAS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_CATEGORIA;
		
		private string _NOMBRE;
		
		private EntitySet<SUPLEMENTOS_CATEGORIAS> _SUPLEMENTOS_CATEGORIAS;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_CATEGORIAChanging(int value);
    partial void OnID_CATEGORIAChanged();
    partial void OnNOMBREChanging(string value);
    partial void OnNOMBREChanged();
    #endregion
		
		public CATEGORIAS()
		{
			this._SUPLEMENTOS_CATEGORIAS = new EntitySet<SUPLEMENTOS_CATEGORIAS>(new Action<SUPLEMENTOS_CATEGORIAS>(this.attach_SUPLEMENTOS_CATEGORIAS), new Action<SUPLEMENTOS_CATEGORIAS>(this.detach_SUPLEMENTOS_CATEGORIAS));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CATEGORIA", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_CATEGORIA
		{
			get
			{
				return this._ID_CATEGORIA;
			}
			set
			{
				if ((this._ID_CATEGORIA != value))
				{
					this.OnID_CATEGORIAChanging(value);
					this.SendPropertyChanging();
					this._ID_CATEGORIA = value;
					this.SendPropertyChanged("ID_CATEGORIA");
					this.OnID_CATEGORIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this.OnNOMBREChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE = value;
					this.SendPropertyChanged("NOMBRE");
					this.OnNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CATEGORIAS_SUPLEMENTOS_CATEGORIAS", Storage="_SUPLEMENTOS_CATEGORIAS", ThisKey="ID_CATEGORIA", OtherKey="ID_CATEGORIA")]
		public EntitySet<SUPLEMENTOS_CATEGORIAS> SUPLEMENTOS_CATEGORIAS
		{
			get
			{
				return this._SUPLEMENTOS_CATEGORIAS;
			}
			set
			{
				this._SUPLEMENTOS_CATEGORIAS.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SUPLEMENTOS_CATEGORIAS(SUPLEMENTOS_CATEGORIAS entity)
		{
			this.SendPropertyChanging();
			entity.CATEGORIAS = this;
		}
		
		private void detach_SUPLEMENTOS_CATEGORIAS(SUPLEMENTOS_CATEGORIAS entity)
		{
			this.SendPropertyChanging();
			entity.CATEGORIAS = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SUPLEMENTOS")]
	public partial class SUPLEMENTOS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_SUPLEMENTO;
		
		private string _NOMBRE;
		
		private string _DESCRIPCION;
		
		private decimal _PRECIO;
		
		private int _CANTIDAD;
		
		private string _RUTA_IMAGEN;
		
		private EntitySet<DETALLE_PEDIDOS> _DETALLE_PEDIDOS;
		
		private EntitySet<SUPLEMENTOS_CATEGORIAS> _SUPLEMENTOS_CATEGORIAS;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_SUPLEMENTOChanging(int value);
    partial void OnID_SUPLEMENTOChanged();
    partial void OnNOMBREChanging(string value);
    partial void OnNOMBREChanged();
    partial void OnDESCRIPCIONChanging(string value);
    partial void OnDESCRIPCIONChanged();
    partial void OnPRECIOChanging(decimal value);
    partial void OnPRECIOChanged();
    partial void OnCANTIDADChanging(int value);
    partial void OnCANTIDADChanged();
    partial void OnRUTA_IMAGENChanging(string value);
    partial void OnRUTA_IMAGENChanged();
    #endregion
		
		public SUPLEMENTOS()
		{
			this._DETALLE_PEDIDOS = new EntitySet<DETALLE_PEDIDOS>(new Action<DETALLE_PEDIDOS>(this.attach_DETALLE_PEDIDOS), new Action<DETALLE_PEDIDOS>(this.detach_DETALLE_PEDIDOS));
			this._SUPLEMENTOS_CATEGORIAS = new EntitySet<SUPLEMENTOS_CATEGORIAS>(new Action<SUPLEMENTOS_CATEGORIAS>(this.attach_SUPLEMENTOS_CATEGORIAS), new Action<SUPLEMENTOS_CATEGORIAS>(this.detach_SUPLEMENTOS_CATEGORIAS));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_SUPLEMENTO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_SUPLEMENTO
		{
			get
			{
				return this._ID_SUPLEMENTO;
			}
			set
			{
				if ((this._ID_SUPLEMENTO != value))
				{
					this.OnID_SUPLEMENTOChanging(value);
					this.SendPropertyChanging();
					this._ID_SUPLEMENTO = value;
					this.SendPropertyChanged("ID_SUPLEMENTO");
					this.OnID_SUPLEMENTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this.OnNOMBREChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE = value;
					this.SendPropertyChanged("NOMBRE");
					this.OnNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="VarChar(200)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this.OnDESCRIPCIONChanging(value);
					this.SendPropertyChanging();
					this._DESCRIPCION = value;
					this.SendPropertyChanged("DESCRIPCION");
					this.OnDESCRIPCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRECIO", DbType="Money NOT NULL")]
		public decimal PRECIO
		{
			get
			{
				return this._PRECIO;
			}
			set
			{
				if ((this._PRECIO != value))
				{
					this.OnPRECIOChanging(value);
					this.SendPropertyChanging();
					this._PRECIO = value;
					this.SendPropertyChanged("PRECIO");
					this.OnPRECIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CANTIDAD", DbType="Int NOT NULL")]
		public int CANTIDAD
		{
			get
			{
				return this._CANTIDAD;
			}
			set
			{
				if ((this._CANTIDAD != value))
				{
					this.OnCANTIDADChanging(value);
					this.SendPropertyChanging();
					this._CANTIDAD = value;
					this.SendPropertyChanged("CANTIDAD");
					this.OnCANTIDADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RUTA_IMAGEN", DbType="VarChar(200)")]
		public string RUTA_IMAGEN
		{
			get
			{
				return this._RUTA_IMAGEN;
			}
			set
			{
				if ((this._RUTA_IMAGEN != value))
				{
					this.OnRUTA_IMAGENChanging(value);
					this.SendPropertyChanging();
					this._RUTA_IMAGEN = value;
					this.SendPropertyChanged("RUTA_IMAGEN");
					this.OnRUTA_IMAGENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SUPLEMENTOS_DETALLE_PEDIDOS", Storage="_DETALLE_PEDIDOS", ThisKey="ID_SUPLEMENTO", OtherKey="ID_SUPLEMENTO")]
		public EntitySet<DETALLE_PEDIDOS> DETALLE_PEDIDOS
		{
			get
			{
				return this._DETALLE_PEDIDOS;
			}
			set
			{
				this._DETALLE_PEDIDOS.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SUPLEMENTOS_SUPLEMENTOS_CATEGORIAS", Storage="_SUPLEMENTOS_CATEGORIAS", ThisKey="ID_SUPLEMENTO", OtherKey="ID_SUPLEMENTO")]
		public EntitySet<SUPLEMENTOS_CATEGORIAS> SUPLEMENTOS_CATEGORIAS
		{
			get
			{
				return this._SUPLEMENTOS_CATEGORIAS;
			}
			set
			{
				this._SUPLEMENTOS_CATEGORIAS.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DETALLE_PEDIDOS(DETALLE_PEDIDOS entity)
		{
			this.SendPropertyChanging();
			entity.SUPLEMENTOS = this;
		}
		
		private void detach_DETALLE_PEDIDOS(DETALLE_PEDIDOS entity)
		{
			this.SendPropertyChanging();
			entity.SUPLEMENTOS = null;
		}
		
		private void attach_SUPLEMENTOS_CATEGORIAS(SUPLEMENTOS_CATEGORIAS entity)
		{
			this.SendPropertyChanging();
			entity.SUPLEMENTOS = this;
		}
		
		private void detach_SUPLEMENTOS_CATEGORIAS(SUPLEMENTOS_CATEGORIAS entity)
		{
			this.SendPropertyChanging();
			entity.SUPLEMENTOS = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VistaSuplementos")]
	public partial class VistaSuplementos
	{
		
		private int _ID_SUPLEMENTO;
		
		private string _NOMBRE;
		
		private string _DESCRIPCION;
		
		private decimal _PRECIO;
		
		private int _CANTIDAD;
		
		private string _NombreCategoria;
		
		private string _RUTA_IMAGEN;
		
		public VistaSuplementos()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_SUPLEMENTO", DbType="Int NOT NULL")]
		public int ID_SUPLEMENTO
		{
			get
			{
				return this._ID_SUPLEMENTO;
			}
			set
			{
				if ((this._ID_SUPLEMENTO != value))
				{
					this._ID_SUPLEMENTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="VarChar(200)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRECIO", DbType="Money NOT NULL")]
		public decimal PRECIO
		{
			get
			{
				return this._PRECIO;
			}
			set
			{
				if ((this._PRECIO != value))
				{
					this._PRECIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CANTIDAD", DbType="Int NOT NULL")]
		public int CANTIDAD
		{
			get
			{
				return this._CANTIDAD;
			}
			set
			{
				if ((this._CANTIDAD != value))
				{
					this._CANTIDAD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreCategoria", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NombreCategoria
		{
			get
			{
				return this._NombreCategoria;
			}
			set
			{
				if ((this._NombreCategoria != value))
				{
					this._NombreCategoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RUTA_IMAGEN", DbType="VarChar(200)")]
		public string RUTA_IMAGEN
		{
			get
			{
				return this._RUTA_IMAGEN;
			}
			set
			{
				if ((this._RUTA_IMAGEN != value))
				{
					this._RUTA_IMAGEN = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
